const state={section:'dashboard',csrf:null,user:null,data:{}};
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function csrf(){const r=await fetch('/api/csrf',{credentials:'include'});const j=await r.json();state.csrf=j.csrfToken;return state.csrf}
async function api(url,opt={}){if(!state.csrf)await csrf();const headers={...(opt.headers||{})};if(opt.body && !(opt.body instanceof FormData))headers['content-type']='application/json';if(opt.method && !['GET','HEAD'].includes(opt.method.toUpperCase()))headers['x-csrf-token']=state.csrf;const r=await fetch(url,{credentials:'include',...opt,headers});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function badge(v){const s=String(v??'');const c=['true','active','available','accepted','paid','done','verified'].includes(s.toLowerCase())?'ok':['false','inactive','cancelled','declined'].includes(s.toLowerCase())?'bad':'warn';return `<span class="badge ${c}">${esc(s)}</span>`}
function money(c){return new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format((Number(c)||0)/100)}
function date(v){return v?new Date(v).toLocaleString('de-DE'):'–'}
function showModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});

async function boot(){try{await csrf();const me=await api('/api/auth/me');if(!me.user?.is_admin)throw new Error('Kein Administrator-Konto');state.user=me.user;$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminIdentity').textContent=me.user.email;await load()}catch(e){$('#loginView').classList.remove('hidden');$('#adminView').classList.add('hidden')}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMsg').textContent='';try{await csrf();const j=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});if(!j.user?.is_admin)throw new Error('Dieses Konto hat keine Admin-Rechte');state.user=j.user;$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminIdentity').textContent=j.user.email;await load()}catch(err){$('#loginMsg').textContent=err.message}});
$('#logoutBtn').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}location.href='/admin'};
$('#refreshBtn').onclick=()=>load();
$('#nav').addEventListener('click',async e=>{const b=e.target.closest('[data-section]');if(!b)return;document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.section=b.dataset.section;$('#pageTitle').textContent=b.textContent;await load()});

async function load(){const c=$('#content');c.innerHTML='<div class="panel">Lade…</div>';try{if(state.section==='dashboard')return renderDashboard(await api('/api/admin/stats'));if(state.section==='companies')return renderCompanies((await api('/api/admin/companies')).companies);if(state.section==='users')return renderUsers((await api('/api/admin/users')).users);if(state.section==='requests')return renderRequests((await api('/api/admin/requests')).requests);if(state.section==='offers')return renderOffers((await api('/api/admin/offers')).offers);if(state.section==='transports')return renderTransports((await api('/api/admin/transports')).transports);if(state.section==='invoices')return renderInvoices((await api('/api/admin/invoices')).invoices);if(state.section==='audit')return renderAudit((await api('/api/admin/audit')).audit)}catch(e){c.innerHTML=`<div class="panel error">${esc(e.message)}</div>`}}
function renderDashboard(s){$('#content').innerHTML=`<div class="grid stats">${Object.entries(s).map(([k,v])=>`<div class="stat"><span class="muted">${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div>`}
function renderCompanies(rows){state.data.companies=rows;$('#content').innerHTML=`<div class="panel"><div class="toolbar"><input id="filter" placeholder="Unternehmen suchen…"></div><table class="table"><thead><tr><th>Unternehmen</th><th>Typ</th><th>E-Mail</th><th>Ort</th><th>Verifiziert</th><th>Benutzer</th><th>Erstellt</th><th>Aktionen</th></tr></thead><tbody id="tbody">${companyRows(rows)}</tbody></table></div>`;$('#filter').oninput=e=>{$('#tbody').innerHTML=companyRows(rows.filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())))}}
function companyRows(rows){return rows.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="muted">${esc(x.id)}</span></td><td>${esc(x.role)}</td><td>${esc(x.email||'')}</td><td>${esc([x.postal_code,x.city,x.country].filter(Boolean).join(' '))}</td><td>${x.is_verified?badge('verified'):badge('false')}</td><td>${x.users}</td><td>${date(x.created_at)}</td><td><div class="actions"><button class="btn small secondary" onclick="editCompany('${x.id}')">Bearbeiten</button><button class="btn small" onclick="toggleVerify('${x.id}',${!x.is_verified})">${x.is_verified?'Verifizierung entfernen':'Verifizieren'}</button></div></td></tr>`).join('')}
window.editCompany=id=>{const x=state.data.companies.find(v=>v.id===id);showModal(`<h3>Unternehmen bearbeiten</h3><form id="companyForm" class="stack"><div><label>Name</label><input name="name" value="${esc(x.name)}"></div><div><label>Rolle</label><select name="role">${['EVU','Wagenhalter','Kranunternehmen','Logistiker','Sonstige'].map(r=>`<option ${r===x.role?'selected':''}>${r}</option>`).join('')}</select></div><div class="actions"><button class="btn">Speichern</button><button type="button" class="btn secondary" onclick="closeModal()">Abbrechen</button></div></form>`);$('#companyForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api(`/api/admin/companies/${id}`,{method:'PATCH',body:JSON.stringify({name:f.get('name'),role:f.get('role')})});closeModal();load()}}
window.toggleVerify=async(id,val)=>{await api(`/api/admin/companies/${id}`,{method:'PATCH',body:JSON.stringify({is_verified:val})});load()}

function renderUsers(rows){state.data.users=rows;$('#content').innerHTML=`<div class="panel"><div class="toolbar"><input id="filter" placeholder="Benutzer suchen…"></div><table class="table"><thead><tr><th>E-Mail</th><th>Unternehmen</th><th>Aktiv</th><th>Admin</th><th>E-Mail bestätigt</th><th>Letzter Login</th><th>Aktionen</th></tr></thead><tbody id="tbody">${userRows(rows)}</tbody></table></div>`;$('#filter').oninput=e=>{$('#tbody').innerHTML=userRows(rows.filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())))}}
function userRows(rows){return rows.map(x=>`<tr><td><b>${esc(x.email)}</b><br><span class="muted">${esc(x.id)}</span></td><td>${esc(x.company_name)}</td><td>${x.is_active?badge('active'):badge('inactive')}</td><td>${x.is_admin?badge('Admin'):'–'}</td><td>${x.email_verified_at?badge('verified'):badge('offen')}</td><td>${date(x.last_login_at)}</td><td><div class="actions"><button class="btn small ${x.is_active?'danger':'secondary'}" onclick="setUser('${x.id}',{is_active:${!x.is_active}})">${x.is_active?'Sperren':'Freigeben'}</button><button class="btn small secondary" onclick="setUser('${x.id}',{is_admin:${!x.is_admin}})">${x.is_admin?'Admin entfernen':'Admin machen'}</button></div></td></tr>`).join('')}
window.setUser=async(id,payload)=>{if(state.user?.id===id && (payload.is_active===false||payload.is_admin===false) && !confirm('Du änderst dein eigenes Admin-Konto. Fortfahren?'))return;await api(`/api/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(payload)});load()}

function renderRequests(rows){$('#content').innerHTML=`<div class="panel"><table class="table"><thead><tr><th>ID</th><th>Unternehmen</th><th>Route</th><th>Titel</th><th>Status</th><th>Zeitraum</th><th>Erstellt</th><th>Aktion</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#TR-${x.public_id}</td><td>${esc(x.company_name)}</td><td>${esc(x.start_location)} → ${esc(x.destination)}</td><td>${esc(x.title)}</td><td>${badge(x.status)}</td><td>${esc(x.from_date||'')} – ${esc(x.to_date||'')}</td><td>${date(x.created_at)}</td><td><select onchange="adminStatus('requests','${x.id}',this.value)">${['draft','new','progress','awarded','cancelled'].map(s=>`<option value="${s}" ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`}
function renderOffers(rows){$('#content').innerHTML=`<div class="panel"><table class="table"><thead><tr><th>Anfrage</th><th>Anbieter</th><th>Preis</th><th>Status</th><th>Gültig bis</th><th>Erstellt</th><th>Aktion</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#TR-${x.public_id}<br>${esc(x.start_location)} → ${esc(x.destination)}</td><td>${esc(x.provider_name)}</td><td>${money(x.price_cents)}</td><td>${badge(x.status)}</td><td>${esc(x.valid_until||'–')}</td><td>${date(x.created_at)}</td><td><select onchange="adminStatus('offers','${x.id}',this.value)">${['pending','accepted','declined','withdrawn'].map(s=>`<option value="${s}" ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`}
function renderTransports(rows){$('#content').innerHTML=`<div class="panel"><table class="table"><thead><tr><th>Route</th><th>Auftraggeber</th><th>Anbieter</th><th>Status</th><th>Termin</th><th>Erstellt</th><th>Aktion</th></tr></thead><tbody>${rows.map(x=>`<tr><td>#TR-${x.public_id}<br>${esc(x.start_location)} → ${esc(x.destination)}</td><td>${esc(x.customer_name)}</td><td>${esc(x.provider_name||'–')}</td><td>${badge(x.status)}</td><td>${esc(x.scheduled_from||'')} – ${esc(x.scheduled_to||'')}</td><td>${date(x.created_at)}</td><td><select onchange="adminStatus('transports','${x.id}',this.value)">${['planned','underway','done','cancelled'].map(s=>`<option value="${s}" ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`}
window.adminStatus=async(type,id,status)=>{await api(`/api/admin/${type}/${id}`,{method:'PATCH',body:JSON.stringify({status})});load()}

function renderInvoices(rows){state.data.invoices=rows;$('#content').innerHTML=`<div class="panel"><div class="section-title"><h3>Rechnungen</h3><button class="btn" onclick="newInvoice()">+ Rechnung</button></div><table class="table"><thead><tr><th>Nr.</th><th>Unternehmen</th><th>Typ</th><th>Betrag</th><th>Datum</th><th>Fällig</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.invoice_number)}</td><td>${esc(x.company_name)}</td><td>${esc(x.type)}</td><td>${money(x.amount_cents)}</td><td>${esc(x.invoice_date)}</td><td>${esc(x.due_date||'–')}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div>`}
window.newInvoice=async()=>{let companies=state.data.companies;if(!companies)companies=(await api('/api/admin/companies')).companies;showModal(`<h3>Rechnung erstellen</h3><form id="invoiceForm" class="stack"><div><label>Unternehmen</label><select name="company_id">${companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div><label>Rechnungsnummer</label><input name="invoice_number" required></div><div><label>Typ</label><input name="type" value="TRASSA Leistung" required></div><div><label>Betrag in EUR</label><input name="amount" type="number" step="0.01" min="0" required></div><div><label>Fällig am</label><input name="due_date" type="date"></div><div class="actions"><button class="btn">Erstellen</button><button type="button" class="btn secondary" onclick="closeModal()">Abbrechen</button></div></form>`);$('#invoiceForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await api('/api/admin/invoices',{method:'POST',body:JSON.stringify({company_id:f.get('company_id'),invoice_number:f.get('invoice_number'),type:f.get('type'),amount_cents:Math.round(Number(f.get('amount'))*100),due_date:f.get('due_date')||undefined})});closeModal();load()}}
window.closeModal=closeModal;
function renderAudit(rows){$('#content').innerHTML=`<div class="panel"><table class="table"><thead><tr><th>Zeit</th><th>Aktion</th><th>Entity</th><th>User</th><th>Company</th><th>IP</th><th>Details</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type||'')} ${esc(x.entity_id||'')}</td><td>${esc(x.user_email||x.user_id||'–')}</td><td>${esc(x.company_name||x.company_id||'–')}</td><td>${esc(x.ip||'')}</td><td><code>${esc(JSON.stringify(x.metadata||{}))}</code></td></tr>`).join('')}</tbody></table></div>`}
boot();
